spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:securevault}
    username: ${DB_USER:svuser}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false